### ISSUE TITLE
Multi-node deployment failing

### ISSUE THREAD

**Issue by pierlauro** [open-io/ansible-playbook-openio-deployment#45]
Hi,
I've followed the [official guide](https://docs.openio.io/latest/source/sandbox-guide/multi_nodes_install.html) for multi-node installation and successfully deployed openio on 3 nodes.

When trying to deploy with an additional node, however, problems started to arise: after commenting [this check](https://github.com/open-io/ansible-playbook-openio-deployment/blob/609417bad0eea9acb78f6064b63428b03f38b56e/products/sds/playbooks/checks.yml#L21) as nodes are supposed to be 4, the deployment fails on zookeeper for unknown reasons.

I am attaching you the last part of the log (with zookeeper failure details) and the `inventory.yml` I am using (exactly the [original one](https://github.com/open-io/ansible-playbook-openio-deployment/blob/609417bad0eea9acb78f6064b63428b03f38b56e/products/sds/inventory.yml), with one more node).

Thank you for your help.

Branch: 19.10
System: Centos 7

**Log**:
```
TASK [zookeeper : register openio_zookeeper_bind_address] *********************************************************************************************************************************************************
Wednesday 18 December 2019  18:27:56 +0100 (0:00:00.924)       0:00:37.224 **** 
ok: [node1]
ok: [node2]
ok: [node3]
ok: [node4]

TASK [zookeeper : Ensure directories exists] **********************************************************************************************************************************************************************
Wednesday 18 December 2019  18:27:56 +0100 (0:00:00.207)       0:00:37.432 **** 
ok: [node2] => (item={'path': '/etc/gridinit.d/OPENIO'})
ok: [node1] => (item={'path': '/etc/gridinit.d/OPENIO'})
ok: [node2] => (item={'path': '/etc/oio/sds/OPENIO/zookeeper-0'})
ok: [node3] => (item={'path': '/etc/gridinit.d/OPENIO'})
ok: [node1] => (item={'path': '/etc/oio/sds/OPENIO/zookeeper-0'})
ok: [node2] => (item={'path': '/mnt/metadata/OPENIO/zookeeper-0'})
ok: [node2] => (item={'path': '/var/log/oio/sds/OPENIO/zookeeper-0', 'owner': 'openio', 'mode': '0750'})
ok: [node4] => (item={'path': '/etc/gridinit.d/OPENIO'})
ok: [node3] => (item={'path': '/etc/oio/sds/OPENIO/zookeeper-0'})
ok: [node1] => (item={'path': '/mnt/metadata/OPENIO/zookeeper-0'})
ok: [node1] => (item={'path': '/var/log/oio/sds/OPENIO/zookeeper-0', 'owner': 'openio', 'mode': '0750'})
ok: [node4] => (item={'path': '/etc/oio/sds/OPENIO/zookeeper-0'})
ok: [node3] => (item={'path': '/mnt/metadata/OPENIO/zookeeper-0'})
ok: [node3] => (item={'path': '/var/log/oio/sds/OPENIO/zookeeper-0', 'owner': 'openio', 'mode': '0750'})
ok: [node4] => (item={'path': '/mnt/metadata/OPENIO/zookeeper-0'})
ok: [node4] => (item={'path': '/var/log/oio/sds/OPENIO/zookeeper-0', 'owner': 'openio', 'mode': '0750'})

TASK [zookeeper : Generate configuration files] *******************************************************************************************************************************************************************
Wednesday 18 December 2019  18:27:57 +0100 (0:00:00.296)       0:00:37.728 **** 
ok: [node1] => (item={'src': 'zookeeper.conf.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/zoo.cfg'})
ok: [node2] => (item={'src': 'zookeeper.conf.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/zoo.cfg'})
ok: [node3] => (item={'src': 'zookeeper.conf.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/zoo.cfg'})
ok: [node4] => (item={'src': 'zookeeper.conf.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/zoo.cfg'})
ok: [node1] => (item={'src': 'log4j.properties.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/log4j.properties'})
ok: [node2] => (item={'src': 'log4j.properties.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/log4j.properties'})
ok: [node3] => (item={'src': 'log4j.properties.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/log4j.properties'})
ok: [node1] => (item={'src': 'java.env.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/java.env'})
ok: [node4] => (item={'src': 'log4j.properties.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/log4j.properties'})
ok: [node2] => (item={'src': 'java.env.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/java.env'})
ok: [node3] => (item={'src': 'java.env.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/java.env'})
ok: [node4] => (item={'src': 'java.env.j2', 'dest': '/etc/oio/sds/OPENIO/zookeeper-0/java.env'})
ok: [node1] => (item={'src': 'gridinit_zookeeper.conf.j2', 'dest': '/etc/gridinit.d//OPENIO-zookeeper-0.conf'})
ok: [node2] => (item={'src': 'gridinit_zookeeper.conf.j2', 'dest': '/etc/gridinit.d//OPENIO-zookeeper-0.conf'})
ok: [node3] => (item={'src': 'gridinit_zookeeper.conf.j2', 'dest': '/etc/gridinit.d//OPENIO-zookeeper-0.conf'})
ok: [node1] => (item={'src': 'myid.j2', 'dest': '/mnt/metadata/OPENIO/zookeeper-0/myid'})
ok: [node4] => (item={'src': 'gridinit_zookeeper.conf.j2', 'dest': '/etc/gridinit.d//OPENIO-zookeeper-0.conf'})
ok: [node2] => (item={'src': 'myid.j2', 'dest': '/mnt/metadata/OPENIO/zookeeper-0/myid'})
ok: [node3] => (item={'src': 'myid.j2', 'dest': '/mnt/metadata/OPENIO/zookeeper-0/myid'})
ok: [node4] => (item={'src': 'myid.j2', 'dest': '/mnt/metadata/OPENIO/zookeeper-0/myid'})

TASK [zookeeper : restart zookeeper to apply the new configuration] ***********************************************************************************************************************************************
Wednesday 18 December 2019  18:27:57 +0100 (0:00:00.460)       0:00:38.189 **** 

TASK [zookeeper : Ensure zookeeper is started] ********************************************************************************************************************************************************************
Wednesday 18 December 2019  18:27:57 +0100 (0:00:00.101)       0:00:38.291 **** 
ok: [node1]
ok: [node2]
ok: [node3]
ok: [node4]

TASK [zookeeper : check zookeeper] ********************************************************************************************************************************************************************************
Wednesday 18 December 2019  18:27:57 +0100 (0:00:00.174)       0:00:38.465 **** 
FAILED - RETRYING: check zookeeper (3 retries left).
FAILED - RETRYING: check zookeeper (3 retries left).
FAILED - RETRYING: check zookeeper (3 retries left).
FAILED - RETRYING: check zookeeper (3 retries left).
FAILED - RETRYING: check zookeeper (2 retries left).
FAILED - RETRYING: check zookeeper (2 retries left).
FAILED - RETRYING: check zookeeper (2 retries left).
FAILED - RETRYING: check zookeeper (2 retries left).
FAILED - RETRYING: check zookeeper (1 retries left).
FAILED - RETRYING: check zookeeper (1 retries left).
FAILED - RETRYING: check zookeeper (1 retries left).
FAILED - RETRYING: check zookeeper (1 retries left).
fatal: [node1]: FAILED! => {"attempts": 3, "changed": false, "cmd": "echo ruok | nc 172.16.20.29 6005", "delta": "0:00:00.017533", "end": "2019-12-18 18:28:13.128098", "msg": "non-zero return code", "rc": 1, "start": "2019-12-18 18:28:13.110565", "stderr": "Ncat: Connection refused.", "stderr_lines": ["Ncat: Connection refused."], "stdout": "", "stdout_lines": []}
fatal: [node2]: FAILED! => {"attempts": 3, "changed": false, "cmd": "echo ruok | nc 172.16.20.3 6005", "delta": "0:00:00.015480", "end": "2019-12-18 18:28:13.156728", "msg": "non-zero return code", "rc": 1, "start": "2019-12-18 18:28:13.141248", "stderr": "Ncat: Connection refused.", "stderr_lines": ["Ncat: Connection refused."], "stdout": "", "stdout_lines": []}
fatal: [node3]: FAILED! => {"attempts": 3, "changed": false, "cmd": "echo ruok | nc 172.16.20.30 6005", "delta": "0:00:00.018154", "end": "2019-12-18 18:28:13.172716", "msg": "non-zero return code", "rc": 1, "start": "2019-12-18 18:28:13.154562", "stderr": "Ncat: Connection refused.", "stderr_lines": ["Ncat: Connection refused."], "stdout": "", "stdout_lines": []}
fatal: [node4]: FAILED! => {"attempts": 3, "changed": false, "cmd": "echo ruok | nc 172.16.20.31 6005", "delta": "0:00:00.016529", "end": "2019-12-18 18:28:13.192209", "msg": "non-zero return code", "rc": 1, "start": "2019-12-18 18:28:13.175680", "stderr": "Ncat: Connection refused.", "stderr_lines": ["Ncat: Connection refused."], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
node1                      : ok=108  changed=0    unreachable=0    failed=1    skipped=42   rescued=0    ignored=0   
node2                      : ok=107  changed=0    unreachable=0    failed=1    skipped=42   rescued=0    ignored=0   
node3                      : ok=107  changed=0    unreachable=0    failed=1    skipped=42   rescued=0    ignored=0   
node4                      : ok=107  changed=0    unreachable=0    failed=1    skipped=42   rescued=0    ignored=0   

```

**inventory.yml**:

```yaml
---
all:
  hosts:
    node1:
      ansible_host: node1
      openio_data_mounts:
        - mountpoint: /mnt/data1
          partition: /dev/sdb1
        - mountpoint: /mnt/data2
          partition: /dev/sdc1
      openio_metadata_mounts:
        - mountpoint: /mnt/metadata
          partition: /dev/sdd1
          meta2_count: 2
    node2:
      ansible_host: node2
      openio_data_mounts:
        - mountpoint: /mnt/data1
          partition: /dev/sdb1
        - mountpoint: /mnt/data2
          partition: /dev/sdc1
      openio_metadata_mounts:
        - mountpoint: /mnt/metadata
          partition: /dev/sdd1
          meta2_count: 2
    node3:
      ansible_host: node3
      openio_data_mounts:
        - mountpoint: /mnt/data1
          partition: /dev/sdb1
        - mountpoint: /mnt/data2
          partition: /dev/sdc1
      openio_metadata_mounts:
        - mountpoint: /mnt/metadata
          partition: /dev/sdd1
          meta2_count: 2
    node4:
      ansible_host: node4
      openio_data_mounts:
        - mountpoint: /mnt/data1
          partition: /dev/sdb1
        - mountpoint: /mnt/data2
          partition: /dev/sdc1
      openio_metadata_mounts:
        - mountpoint: /mnt/metadata
          partition: /dev/sdd1
          meta2_count: 2
  vars:
    ansible_user: root
    #ansible_user: ubuntu
    #ansible_user: centos

    # Disable check of mountpoint matching
    openio_checks_filter:
      mountpoint: false

  children:
    openio:
      children:
        fronts: {}
        backs: {}

      vars:
        namespace: OPENIO
        namespace_storage_policy: "THREECOPIES"

        openio_bind_interface: '{{ ansible_default_ipv4.alias }}'
        openio_bind_address: '{{ ansible_default_ipv4.address }}'

        openio_oioswift_users:
          - name: "demo:demo"
            password: "DEMO_PASS"
            roles:
              - admin

        # Credentials for private features
        openio_repositories_credentials: {}

    # what is not used for storage
    fronts:
      hosts: {}

    # what is used for storage
    backs:
      hosts:
        node1: {}
        node2: {}
        node3: {}
        node4: {}

### SDS
    account:
      children:
        backs: {}

    beanstalkd:
      children:
        backs: {}

    conscience:
      hosts:
        node3: {}

    conscience-agent:
      children:
        backs: {}

    ecd:
      children:
        backs: {}

    meta:
      children:
        meta0: {}
        meta1: {}
        meta2: {}
        meta3: {}

    meta0:
      hosts:
        node1: {}
        node2: {}
        node3: {}
        node4: {}

    meta1:
      hosts:
        node1: {}
        node2: {}
        node3: {}
        node4: {}

    meta2:
      hosts:
        node1: {}
        node2: {}
        node3: {}
        node4: {}

    meta3:
      hosts:
        node1: {}
        node2: {}
        node3: {}
        node4: {}

    namespace:
      children:
        openio: {}
      vars:
        openio_namespace_conscience_url: "{{ hostvars[groups['conscience'][0]]['openio_bind_address'] }}:6000"

    oio-blob-indexer:
      children:
        backs: {}

    oio-blob-rebuilder:
      children:
        backs: {}

    oio-event-agent:
      children:
        backs: {}

    oioproxy:
      children:
        openio: {}

    oioswift:
      children:
        backs: {}
      vars:
        openio_oioswift_pipeline: "{{ pipeline_tempauth }}"
        openio_oioswift_filter_tempauth:
          "{{ {'use': 'egg:oioswift#tempauth'} | combine(openio_oioswift_users | dict_to_tempauth) }}"
    rawx:
      children:
        backs: {}

    rdir:
      children:
        backs: {}

    redis:
      hosts:
        node1: {}
        node2: {}
        node3: {}
        node4: {}

    zookeeper:
      hosts:
        node1: {}
        node2: {}
        node3: {}
        node4: {}

### OIOFS
    oiofs:
      hosts: {}
      vars: {}

    oiofs_redis:
      hosts: {}
...

```
